"""
Django settings for privux project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

KEYCLOAK_ISSUER = os.environ.get("KEYCLOAK_ISSUER", "")
if not KEYCLOAK_ISSUER:
    import warnings
    warnings.warn(
        "KEYCLOAK_ISSUER is not set. SSO login will fail. "
        "Set KEYCLOAK_ISSUER=https://<your-keycloak>/realms/<realm> in your environment.",
        stacklevel=2,
    )
KEYCLOAK_CLIENT_ID = os.environ.get("KEYCLOAK_CLIENT_ID", "")

_frame_ancestors_env = os.environ.get("FRAME_ANCESTORS", "")
if not _frame_ancestors_env:
    import warnings
    warnings.warn(
        "FRAME_ANCESTORS is not set. SSO iframe embedding will not work. "
        "Set FRAME_ANCESTORS in your .env (local) or environment (production).",
        stacklevel=2,
    )
FRAME_ANCESTORS = _frame_ancestors_env.split()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-e+dfmqm))kmz9k*e4dt(0=)(=uxc0z9hzmfar1-pif#1r=npin"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS", "localhost,127.0.0.1,dips.soton.ac.uk"
).split(",")

CSRF_TRUSTED_ORIGINS = os.environ.get(
    "CSRF_TRUSTED_ORIGINS", "https://dips.soton.ac.uk"
).split(",")

CORS_ALLOWED_ORIGINS = os.environ.get(
    "CORS_ALLOWED_ORIGINS", "https://dips.soton.ac.uk"
).split(",")
JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "Super Admin",
    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "Admin",
    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": "",
    # Copyright on the footer
    "copyright": "Tek Raj Chhetri",
    # Links to put along the top menu
    "topmenu_links": [
        # Url that gets reversed (Permissions can be added)
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        # model admin to link to (Permissions checked against model)
        {"model": "custom_accounts.User"},
    ],
}
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # installed custom
    "django_summernote",
    # user created
    'corsheaders',
    "custom_accounts",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    # user custom
    "custom_accounts.redirect_user_middleware.FrameAncestorsMiddleware",
    "custom_accounts.redirect_user_middleware.UserRedirectMiddleware",
]

ROOT_URLCONF = "privux.urls"
SESSION_COOKIE_NAME = "policy_editor_sessionid"
# "None" + Secure=True required for cross-site iframe (production HTTPS).
# Modern browsers exempt localhost from the Secure restriction, so dev HTTP works too.
# Override via env vars if needed (e.g. COOKIE_SAMESITE=Lax for plain HTTP servers).
SESSION_COOKIE_SAMESITE = os.environ.get("COOKIE_SAMESITE", "None")
SESSION_COOKIE_SECURE = os.environ.get("COOKIE_SECURE", "True") == "True"
CSRF_COOKIE_SAMESITE = os.environ.get("COOKIE_SAMESITE", "None")
CSRF_COOKIE_SECURE = os.environ.get("COOKIE_SECURE", "True") == "True"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "custom_accounts.context_processors.sso_config",
            ],
        },
    },
]

WSGI_APPLICATION = "privux.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


EMAIL_USE_TLS = True
EMAIL_HOST = "mail.mail.com"
EMAIL_HOST_USER = "no-reply@mail.com"
EMAIL_HOST_PASSWORD = "asfsdfsdf"
EMAIL_PORT = 587

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

#STATIC_URL = "static/"
STATIC_URL = '/policy-editor/static/'
MEDIA_URL = '/policy-editor/media/'

STATICFILES_DIRS = [os.path.join(BASE_DIR, "privux/static")]
STATIC_ROOT = os.path.join(BASE_DIR, "static")

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
#MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
AUTH_USER_MODEL = "custom_accounts.User"
